kind: pipeline
name: default

steps:
- name: Drone Next
  image: docker/compose
  commands:
    - echo Hello World
    - docker-compose -v

- name: docker-build
  image: docker
  volumes:
  - name: cache
    path: /var/run/docker.sock
  commands:
    - docker build -t nextjs .

volumes:
- name: cache
  host:
    path: /var/run/docker.sock