kind: pipeline
name: default

steps:
- name: Drone Next
  image: docker
  commands:
    - echo Hello World update
    - docker -v

- name: Drone Next compose
  image: docker/compose
  commands:
    - echo compose
    - docker-compose -v