kind: pipeline
name: default

steps:
- name: Drone Next
  image: docker
  commands:
    - echo Hello World update
    - docker build -t nextjs-docker .
    # - docker-compose -f docker-compose.yml up -d
