kind: pipeline
name: default

steps:
- name: Drone Next
  image: docker/compose
  commands:
    - echo Hello World update
    - docker-compose -v

- name: Drone Next deploy
  image: docker
  commands:
    # - docker-compose -p nextjs down
    # - docker-compose -p nextjs up -d
    - docker build -t nextjs-docker .