kind: pipeline
name: default

steps:
- name: Drone Next
  image: node
  commands:
    - echo Hello World update
    - yarn
    - yarn build

---

kind: pipeline
type: ssh
name: ssh

steps:
- name: Drone Next SSH
  commands:
    - echo ssh
    - ls