kind: pipeline
name: default

steps:
- name: Drone Next
  image: docker
  commands:
    - echo Hello World update
    - docker -v
    - docker-compose -v

- name: Drone Next deploy
  image: docker/compose
  commands:
    - docker-compose -p nextjs down
    - docker-compose -p nextjs up -d