kind: pipeline
name: default

steps:
- name: docker deploy
  image: docker/compose
  volumes:
  - name: cache
    path: /var/run/docker.sock
  commands:
    - docker-compose down
    # - docker-compose up -d
    - docker-compose up --force-recreate --build -d

volumes:
- name: cache
  host:
    path: /var/run/docker.sock