kind: pipeline
name: default

steps:
- name: Drone Next
  image: docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - echo Hello World update
    - docker build -t nextjs-docker .
    # - docker-compose -f docker-compose.yml up -d
