kind: pipeline
name: docker

steps:
- name: Drone Next
  immage: docker
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - echo Hello World update
    - docker build -t nextjs-docker .
    # - docker-compose -f docker-compose.yml up -d
